### ISSUE TITLE
Add panels (ios) as an OPDS reader.

### ISSUE THREAD

**Issue by Darkwolf1515** [gotson/komga-website#14]
Works great, and is the nicest looking comic client on iOS, even shows up as komga with an icon and everything 
![4461A6FD-67AE-4F2F-95E5-845E666A29B5](https://user-images.githubusercontent.com/65789901/92075761-0b4cf600-ed6e-11ea-90b5-33ba0df99c9c.png)

Should be added to this page https://komga.org/guides/opds.html

**Comment by gotson** [comment]
Does it support OpenSearch ?
