### ISSUE TITLE
Add ability to upload file

### ISSUE THREAD

**Issue by frakman1** [gotson/komga-website#18]
When using the demo page at `https://demo.komga.org`, it would be more useful to allow the user to upload a file to see how it looks and if it's worth installing. I'd rather know what *my* file looks like in the viewer than a demo file.

**Comment by Kussie** [comment]
I'm not sure how the project maintainer feels on the subject.  But that is a fair bit of work just for the demo for little benefit.  

It also opens him and the hosting up to potential legal issues if people upload copyrighted or pornographic content.  Plus it's easy enough to set it up as a trial using docker and the like

**Comment by frakman1** [comment]
OK, Most of these trial/demo instances get spun up for a few hours so I didn't think it would be an issue if someone used questionable material. But I see that it's a 14 day trial so maybe not.
