### ISSUE TITLE
FreeNAS/TrueNAS Jails Tutorial linked in installation is outdated / obsolete

### ISSUE THREAD

**Issue by SleepingPanda** [gotson/komga-website#27]
The FreeNAS tutorial linked on the website doesn't seem to work for me in TrueNAS 12, possibly due to changes in the OS since the guide was made. The specific issues I've encountered occur when starting/stopping the Komga jail. IOCAGE stops functioning and prevents other jails from starting up/shutting down resulting in a lot of challenges.

I wanted to figure out a way around these issues so I wrote a config file for [PM2](https://pm2.keymetrics.io/) to run Komga on jail startup. Other benefits of PM2 include showing you the status of your Komga server and the resources it's currently using with simple commands.

I think there may be a way to get Komga to start natively with an rc script but I'm unfamiliar with that system and couldn't find a guide or similar solutions that successfully worked for me. I'm certain there are other methods I've overlooked as well!

---------------------------------------------------------------------------------------------------

### Create a pkg.json file containing everything your jail needs to install and run Komga.
`echo '{"pkgs":["openjdk11-jre","nano","ca_root_nss","yarn"]}' > /tmp/pkg.json`

### Using that file we just made, create the jail with IOCAGE. Replace `<KOMGA>` with the IP you want the Komga server to have on your network and `<ROUTER>` with the address of your network's router.
`iocage create -n "komga" -p /tmp/pkg.json -r 12.2-RELEASE ip4_addr="vnet0|<KOMGA>/24" defaultrouter="<ROUTER>" vnet="on" allow_raw_sockets="1" boot="on"`

### We can now safely delete that file we created earlier.
`rm /tmp/pkg.json`

### Make a config directory to store Komga, its config files, the database and logs.
`iocage exec komga mkdir -p /config/komga`

### Make the comics directory where Komga will find your comics.
`iocage exec komga mkdir -p /comics`

### Link the config directory we just made to a safe location outside of the jail in case you want to destroy and remake the jail later without losing your database and logs. Make sure to replace `<STORAGE>` with a location you're comfortable with.
`iocage fstab -a komga /mnt/<STORAGE>/komga /config nullfs rw 0 0`

### Link the comics directory we made earlier to the comics directory stored on your TrueNAS server so Komga can read and write them. If you only want Komga to read your files, but not write to them, you can change "rw" to "ro".
`iocage fstab -a komga /mnt/<COMICS_DIR> /comics nullfs rw 0 0`

### Next we must stop the jail, set its mounting options for java 11 to work properly and restart the jail.
`iocage stop komga`
`iocage set mount_fdescfs=1 komga`
`iocage set mount_procfs=1 komga`
`iocage start komga`

### Download Komga to the jail and make it executable.
`iocage exec komga fetch https://github.com/gotson/komga/releases/download/v0.106.1/komga-0.106.1.jar -o /config/komga/komga-latest.jar`
`iocage exec komga chmod u+x /config/komga/komga-latest.jar`

### Next we install PM2 and tell it to startup with the jail automatically.
`iocage exec komga yarn global add pm2`
`iocage exec komga pm2 startup`

###  Now we create both the application.yml file Komga requires and the ecosystem.config.js file PM2 requires:
`iocage exec komga nano`
### Paste the below into nano after you've modified the values as needed [according to the website's instructions](https://komga.org/installation/configuration.html) and save the file to `/config/komga/application.yml`:

komga:
&ensp;&ensp;remember-me:
&ensp;&ensp;&ensp;&ensp;key: somerandomkey1245
&ensp;&ensp;&ensp;&ensp;validity: 2592000
&ensp;&ensp;database:
&ensp;&ensp;&ensp;&ensp;file: /config/komga/database.sqlite
server:
&ensp;&ensp;port: 80
logging:
&ensp;&ensp;file:
&ensp;&ensp;&ensp;&ensp;name: /config/komga/komga.log
&ensp;&ensp;&ensp;&ensp;max-history: 5

### Paste the below into nano and save the file as `/config/komga/ecosystem.config.js`:

module.exports = {
&ensp;&ensp;&ensp;&ensp;&ensp;"apps":[
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;{
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;"name":"Komga",
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;"script":"java",
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;"cwd":"/config/komga",
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;"args":[
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;"-jar",
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;"/config/komga/komga-latest.jar"
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;],
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;"watch":[
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;"/config/komga/komga-latest.jar"
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;],
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;"node_args":[],
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;"log_date_format":"YYYY-MM-DD HH:mm Z",
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;"exec_interpreter":"none",
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;"exec_mode":"fork"
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;}
&ensp;&ensp;&ensp;&ensp;]
}

### Run Komga and save your settings:
`iocage exec komga pm2 start /config/komga/ecosystem.config.js`
`iocage exec komga pm2 save`

### If you want to see the status of the Komga server you can use this command:
`iocage exec komga pm2 status`

### Or to restart Komga, use:
`iocage exec komga pm2 restart Komga`

### Komga is now accessible from the LAN IP you used to make the jail and the port number you used in application.yml. Enjoy!

**Comment by gotson** [comment]
Hello,

It's an externally linked tutorial, so nothing I support officially, and there's not much I can do about it really. You can contact the author of the tutorial directly, that's probably a better course of action.

**Comment by SleepingPanda** [comment]
Hi, thanks for your response! I understand the tutorial linked on the website isn't under your control but maybe you can add a note near it saying it may not work on current/newer versions of TrueNAS? I was pulling my hair out thinking there was something wrong with my server until I realized that.

**Comment by gotson** [comment]
I have no way to assess what's the status of that tutorial as I don't have or own a freenas device. I could remove the link entirely maybe?

**Comment by SleepingPanda** [comment]
Please don't remove the link. I'm just a TrueNAS user notifying you that it that may confuse others. If it wasn't there to begin with, I may not have thought Komga would work _at all_ with TrueNAS and I wouldn't have given Komga a try.

If you still think the only solution is to remove it then I'll ask you to please close this issue instead.

**Comment by gotson** [comment]
I am just asking. You say the link is good to be here, but also it's not working, so 🤷🏻
