### ISSUE TITLE
Issue with link on paperback.md

### ISSUE THREAD

**Issue by sntrenter** [gotson/komga-website#84]
https://github.com/gotson/komga-website/blob/master/website/docs/guides/paperback.md

the extension ver 1.2.10 seems to be broken, you need to use version 1.2.12
the komga website links to the 1.2.10 extentsion. 

using ver 1.2.10 was giving me a 401 error when logging in.

**Comment by gotson** [comment]
feel free to send a PR with the correct link

**Comment by sntrenter** [comment]
https://github.com/gotson/komga-website/pull/85
